//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int ID { get; set; }
        public string Subject_Title { get; set; }
        public int Group_NumberOfGroup { get; set; }
    
        public virtual StudentGroup StudentGroup { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
